
export const mockWeatherData = {
  temperature: 22,
  feelsLike: 25,
  condition: "parcialmente nublado",
  humidity: 65,
  windSpeed: 12,
  visibility: 10,
  pressure: 1013,
  uvIndex: 6,
  sunrise: "07:23",
  sunset: "19:45",
  hourlyTemp: [
    { time: "00:00", temp: 18 },
    { time: "03:00", temp: 16 },
    { time: "06:00", temp: 15 },
    { time: "09:00", temp: 19 },
    { time: "12:00", temp: 22 },
    { time: "15:00", temp: 25 },
    { time: "18:00", temp: 23 },
    { time: "21:00", temp: 20 },
  ],
  hourlyHumidity: [
    { time: "00:00", humidity: 78 },
    { time: "03:00", humidity: 82 },
    { time: "06:00", humidity: 85 },
    { time: "09:00", humidity: 70 },
    { time: "12:00", humidity: 65 },
    { time: "15:00", humidity: 58 },
    { time: "18:00", humidity: 62 },
    { time: "21:00", humidity: 68 },
  ],
  hourlyWind: [
    { time: "00:00", speed: 8 },
    { time: "03:00", speed: 6 },
    { time: "06:00", speed: 5 },
    { time: "09:00", speed: 10 },
    { time: "12:00", speed: 12 },
    { time: "15:00", speed: 15 },
    { time: "18:00", speed: 13 },
    { time: "21:00", speed: 9 },
  ],
  hourlyPressure: [
    { time: "00:00", pressure: 1015 },
    { time: "03:00", pressure: 1014 },
    { time: "06:00", pressure: 1013 },
    { time: "09:00", pressure: 1012 },
    { time: "12:00", pressure: 1013 },
    { time: "15:00", pressure: 1014 },
    { time: "18:00", pressure: 1015 },
    { time: "21:00", pressure: 1016 },
  ],
};

export const mockForecastData = [
  {
    date: "Hoy",
    day: "Miércoles",
    condition: "parcialmente nublado",
    high: 25,
    low: 16,
    humidity: 65,
    windSpeed: 12,
    precipitation: 20,
  },
  {
    date: "19 Jun",
    day: "Jueves",
    condition: "soleado",
    high: 28,
    low: 18,
    humidity: 55,
    windSpeed: 8,
    precipitation: 0,
  },
  {
    date: "20 Jun",
    day: "Viernes",
    condition: "lluvioso",
    high: 21,
    low: 14,
    humidity: 80,
    windSpeed: 15,
    precipitation: 85,
  },
  {
    date: "21 Jun",
    day: "Sábado",
    condition: "nublado",
    high: 19,
    low: 12,
    humidity: 70,
    windSpeed: 10,
    precipitation: 40,
  },
  {
    date: "22 Jun",
    day: "Domingo",
    condition: "soleado",
    high: 26,
    low: 17,
    humidity: 50,
    windSpeed: 6,
    precipitation: 0,
  },
  {
    date: "23 Jun",
    day: "Lunes",
    condition: "parcialmente nublado",
    high: 24,
    low: 16,
    humidity: 60,
    windSpeed: 9,
    precipitation: 10,
  },
  {
    date: "24 Jun",
    day: "Martes",
    condition: "tormentoso",
    high: 22,
    low: 15,
    humidity: 85,
    windSpeed: 18,
    precipitation: 90,
  },
  {
    date: "25 Jun",
    day: "Miércoles",
    condition: "soleado",
    high: 27,
    low: 19,
    humidity: 45,
    windSpeed: 7,
    precipitation: 0,
  },
];

export const mockAlerts = [
  {
    title: "Aviso de Viento Fuerte",
    description: "Se esperan vientos de hasta 45 km/h durante la tarde.",
    level: "medium" as const,
    time: "Hace 2 horas",
  },
  {
    title: "Índice UV Alto",
    description: "Se recomienda usar protector solar y evitar la exposición prolongada al sol.",
    level: "low" as const,
    time: "Hace 4 horas",
  },
  {
    title: "Posible Lluvia",
    description: "20% de probabilidad de lluvia ligera durante la noche.",
    level: "low" as const,
    time: "Hace 6 horas",
  },
];
